ALTER TABLE [dbo].[TasksXRequirements]
    ADD CONSTRAINT [PK_TasksXRequirements] PRIMARY KEY CLUSTERED ([TaskId] ASC, [RequirementId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

