ALTER TABLE [dbo].[UseCaseXRequirements]
    ADD CONSTRAINT [PK_UseCaseXRequirements] PRIMARY KEY CLUSTERED ([RequirementId] ASC, [UseCaseId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

