//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4952
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dogbert.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StaticValues {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StaticValues() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dogbert.Core.Resources.StaticValues", typeof(StaticValues).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tab-7.
        /// </summary>
        public static string Tab_Actors {
            get {
                return ResourceManager.GetString("Tab_Actors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tab-1.
        /// </summary>
        public static string Tab_ProjectDetails {
            get {
                return ResourceManager.GetString("Tab_ProjectDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tab-5.
        /// </summary>
        public static string Tab_ProjectFiles {
            get {
                return ResourceManager.GetString("Tab_ProjectFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tab-2.
        /// </summary>
        public static string Tab_ProjectText {
            get {
                return ResourceManager.GetString("Tab_ProjectText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tab-6.
        /// </summary>
        public static string Tab_RequirementCategories {
            get {
                return ResourceManager.GetString("Tab_RequirementCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tab-3.
        /// </summary>
        public static string Tab_Requirements {
            get {
                return ResourceManager.GetString("Tab_Requirements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tab-4.
        /// </summary>
        public static string Tab_UseCases {
            get {
                return ResourceManager.GetString("Tab_UseCases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tab-1.
        /// </summary>
        public static string UCTab_UCDetails {
            get {
                return ResourceManager.GetString("UCTab_UCDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tab-4.
        /// </summary>
        public static string UCTab_UCRelatedRequirements {
            get {
                return ResourceManager.GetString("UCTab_UCRelatedRequirements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tab-3.
        /// </summary>
        public static string UCTab_UCRelatedUseCases {
            get {
                return ResourceManager.GetString("UCTab_UCRelatedUseCases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tab-2.
        /// </summary>
        public static string UCTab_UCSteps {
            get {
                return ResourceManager.GetString("UCTab_UCSteps", resourceCulture);
            }
        }
    }
}
